#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"
yarn --no-install commitlint --edit "$1"
npm --no-install commitlint --edit "$1"
npx --no-install commitlint --edit "$1"
npx --no-install commitlint --edit "$1"
npx --no-install commitlint --edit ""
yarn --no-install commitlint --edit "$1"
